# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 293d3f6dd15106432ffae55b53d11d9545357ce0bca32784eb1fdf8711fccfb6a0788eba7fc21a0542d3d2c848bc46130d71cda3e96969b62992af8c3972e1ca

test:
  secret_key_base: a5625788089fd7bcf7ce3717dea69cc182598ed6c95852fe5d02da315f7af7d9f1401d2d633622d64090fb8469a033bdddd76302a31b9031ea9a6672bb9ded1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
